export enum IconName {
  LEFT_ARROW = 'left-arrow',
  RIGHT_ARROW = 'right-arrow',
  MOON = 'moon',
  SUN = 'sun',
  JAVASCRIPT = 'javascript',
  TYPESCRIPT = 'typescript',
  REACT = 'react',
  REDUX = 'redux',
  HTML = 'html',
  CSS = 'css',
  ANGULAR = 'angular',
  POSTGRES = 'postgres',
  INSTAGRAM = 'instagram',
  TELEGRAM = 'telegram',
  LINKEDIN = 'linkedin',
}
